# Generated by Django 3.2 on 2021-05-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_carts_price_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='carts',
            name='price_total',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='carts',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
