# Generated by Django 3.2 on 2021-05-09 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_auto_20210509_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='total',
        ),
    ]
