# Generated by Django 3.2 on 2021-05-09 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_remove_carts_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.IntegerField(default=datetime.date(2021, 5, 9), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.IntegerField(default=datetime.time(13, 19, 58, 728457), null=True),
        ),
    ]
